<?php
/**
 * AccountManagerRepository File Doc Comment
 *
 * PHP version 7.1
 *
 * @category AccountManagerRepository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
namespace AppBundle\Repository;

/**
 * AccountManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category Repository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
class AccountManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
