<?php

namespace AppBundle\Repository;

/**
 * AccountManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
