<?php
/**
 * ActivityRepository File Doc Comment
 *
 * PHP version 7.1
 *
 * @category ActivityRepository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
namespace AppBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category Repository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
