<?php
/**
 * ContractRepository File Doc Comment
 *
 * PHP version 7.2
 *
 * @category ContractRepository
 * @package  Repository
 * @author   WildCodeSchool <contact@wildcodeschool.fr>
 */
namespace AppBundle\Repository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category ContractRepository
 * @package  Repository
 * @author   WildCodeSchool <contact@wildcodeschool.fr>
 */
class ContractsRepository extends \Doctrine\ORM\EntityRepository
{
}
