<?php
/**
 * OfferRepository File Doc Comment
 *
 * PHP version 7.1
 *
 * @category OfferRepository
 * @package  Repository
 * @author   WildCodeSchool <contact@wildcodeschool.fr>
 */
namespace AppBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category OfferRepository
 * @package  Repository
 * @author   WildCodeSchool <contact@wildcodeschool.fr>
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $data
     * @return mixed
     */
    public function search($data)
    {
        $query = $this->createQueryBuilder('off')
            ->select('off')
            ->where('off.amount LIKE :data')
            ->orWhere('off.date LIKE :data')
            ->setParameter('data', '%'.$data.'%')
            ->getQuery();

        return $query->getResult();
    }
}
