<?php
/**
 * OfferRepository File Doc Comment
 *
 * PHP version 7.1
 *
 * @category OfferRepository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
namespace AppBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category Repository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
}
