<?php
/**
 * OrganizationRepository File Doc Comment
 *
 * PHP version 7.2
 *
 * @category OrganizationRepository
 * @package  Controller
 * @author   WildCodeSchool <contact@wildcodeschool.fr>
 */
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category OrganizationRepository
 * @package  Controller
 * @author   WildCodeSchool <contact@wildcodeschool.fr>
 */
class OrganizationRepository extends EntityRepository
{
    /**
     * Create a query to search organization per name
     *
     * @param string $data Parameters customers given
     *
     * @return mixed Return result of the query
     */
    public function search($data)
    {
        $query = $this->createQueryBuilder('org')
            ->select('org')
            ->where('org.name LIKE :data')
            ->orWhere('org.description LIKE :data')
            ->setParameter('data', '%'.$data.'%')
            ->getQuery();

        return $query->getResult();
    }
}
