<?php

namespace AppBundle\Repository;

/**
 * organizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class organizationRepository extends \Doctrine\ORM\EntityRepository
{
}
