<?php
/**
 * UserRepository File Doc Comment
 *
 * PHP version 7.1
 *
 * @category UserRepository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category Repository
 * @package  Repository
 * @author   WildCodeSchool <www.wildcodeschool.fr>
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
