<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * AccountManager
 *
 * @ORM\Table(name="account_manager")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AccountManagerRepository")
 */
class AccountManager
{
    /*
     * Relationship Mapping Metadata
     */
    /**
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Offer", mappedBy="managerOffer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $managerOffers;

    /**
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Organization", mappedBy="managerOrganization")
     * @ORM\JoinColumn(nullable=false)
     */
    private $managerOrganizations;

    /*
     * Autogenerated methods / variables
     */
    /**
     *
     * @var int
     *
     * @ORM\Column(name="id",               type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="firstName", type="string", length=32)
     *
     * @Assert\NotBlank(
     *     message = "Veuillez saisir un prénom"
     * )
     * @Assert\Length(
     *     min = 2,
     *     max = 32,
     *     minMessage = "Votre nom doit contenir au mmoins {{ limit }} caractères",
     *     maxMessage = "Votre nom ne peut pas contenir plus de {{ limit }} caractères"
     * )
     */
    private $firstName;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="lastName", type="string", length=32)
     *
     * @Assert\NotBlank(
     *     message = "Veuillez saisir un nom"
     * )
     * @Assert\Length(
     *     min = 2,
     *     max = 32,
     *     minMessage = "Votre nom doit contenir au mmoins {{ limit }} caractères",
     *     maxMessage = "Votre nom ne peut pas contenir plus de {{ limit }} caractères"
     * )
     */
    private $lastName;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="phoneNumber", type="string", length=32)
     *
     * @Assert\Type("string")
     * @Assert\NotBlank(
     *     message = "Veuillez saisir un numéro de téléphone"
     * )
     * @Assert\Length(
     *     min = 9,
     *     max = 32,
     *     exactMessage = "Veuillez saisir un numéro de téléphone valide"
     * )
     * @Assert\Regex(
     *     pattern = "/^(0|\+33)[1-9]([-. ]?[0-9]{2}){4}$/",
     *     message = "Veuillez saisir un numéro de téléphone valide"
     * )
     */
    private $phoneNumber;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=64)
     *
     * @Assert\Type("string")
     * @Assert\NotBlank(
     *     message = "Veuillez saisir une adresse mail"
     * )
     * @Assert\Length(
     *     min = 5,
     *     max = 64,
     *     minMessage = "Votre adresse mail doit contenir au mmoins {{ limit }} caractères",
     *     maxMessage = "Votre adresse mail ne peut pas contenir plus de {{ limit }} caractères"
     * )
     * @Assert\Email(
     *     message = "l'email '{{ value }}' n'est pas valide.",
     *     checkMX = true
     * )
     * @Assert\Regex(
     *     pattern = "/^[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]{2,}\.[a-z]{2,4}$/",
     *     message = "Veuillez saisir une adresse mail valide"
     * )
     */
    private $email;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=64)
     *
     * @Assert\Regex(pattern="/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$/",
     * message="Le mot de passe doit au moins contenir 6 caractères alphanumériques dont au moins un chiffre.")
     */
    private $password;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return AccountManager
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     *
     * @return AccountManager
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set phoneNumber
     *
     * @param string $phoneNumber
     *
     * @return AccountManager
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * Get phoneNumber
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return AccountManager
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return AccountManager
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->managerOffers = new \Doctrine\Common\Collections\ArrayCollection();
        $this->managerOrganizations = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add managerOffer
     *
     * @param \AppBundle\Entity\Offer $managerOffer
     *
     * @return AccountManager
     */
    public function addManagerOffer(Offer $managerOffer)
    {
        $this->managerOffers[] = $managerOffer;

        return $this;
    }

    /**
     * Remove managerOffer
     *
     * @param \AppBundle\Entity\Offer $managerOffer
     */
    public function removeManagerOffer(Offer $managerOffer)
    {
        $this->managerOffers->removeElement($managerOffer);
    }

    /**
     * Get managerOffers
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getManagerOffers()
    {
        return $this->managerOffers;
    }

    /**
     * Add managerOrganization
     *
     * @param \AppBundle\Entity\Organization $managerOrganization
     *
     * @return AccountManager
     */
    public function addManagerOrganization(Organization $managerOrganization)
    {
        $this->managerOrganizations[] = $managerOrganization;

        return $this;
    }

    /**
     * Remove managerOrganization
     *
     * @param \AppBundle\Entity\Organization $managerOrganization
     */
    public function removeManagerOrganization(Organization $managerOrganization)
    {
        $this->managerOrganizations->removeElement($managerOrganization);
    }

    /**
     * Get managerOrganizations
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getManagerOrganizations()
    {
        return $this->managerOrganizations;
    }
}
