<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Contracts
 *
 * @ORM\Table(name="contracts")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ContractsRepository")
 */
class Contracts
{
    /*
     * Relationship Mapping Metadata
     */

    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Organization", inversedBy="contracts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organization;

    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Offer", inversedBy="contracts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $offer;

    /*
     * Autogenerated methods / variables
     */

    /**
     *
     * @var int
     *
     * @ORM\Column(name="id",               type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @var array
     *
     * @ORM\Column(name="uploadPdf", type="array", nullable=true)
     */
    private $uploadPdf;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="finalDeal", type="integer", nullable=true)
     */
    private $finalDeal;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set uploadPdf.
     *
     * @param string $uploadPdf
     *
     * @return Contracts
     */
    public function setUploadPdf($uploadPdf)
    {
        $this->uploadPdf = $uploadPdf;

        return $this;
    }

    /**
     * Get uploadPdf.
     *
     * @return array
     */
    public function getUploadPdf()
    {
        return $this->uploadPdf;
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return Contracts
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set organization.
     *
     * @param \AppBundle\Entity\Organization $organization
     *
     * @return Contracts
     */
    public function setOrganization(Organization $organization = null)
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * Get organization.
     *
     * @return \AppBundle\Entity\Organization
     */
    public function getOrganization()
    {
        return $this->organization;
    }

    /**
     * Set offer.
     *
     * @param \AppBundle\Entity\Offer $offer
     *
     * @return Contracts
     */
    public function setOffer(Offer $offer = null)
    {
        $this->offer = $offer;

        return $this;
    }

    /**
     * Get offer.
     *
     * @return \AppBundle\Entity\Offer
     */
    public function getOffer()
    {
        return $this->offer;
    }

    /**
     * Set finalDeal.
     *
     * @param int $finalDeal
     *
     * @return Contracts
     */
    public function setFinalDeal($finalDeal)
    {
        $this->finalDeal = $finalDeal;

        return $this;
    }

    /**
     * Get finalDeal.
     *
     * @return int
     */
    public function getFinalDeal()
    {
        return $this->finalDeal;
    }
}
