<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Offer
 *
 * @ORM\Table(name="offer")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\OfferRepository")
 */
class Offer
{
    /*
     * Relationship Mapping Metadata
     */

    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Organization", inversedBy="offers")
     * @ORM\JoinColumn(nullable=true)
     */
    private $organization;

    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Activity", inversedBy="activities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $activity;

    /*
     * Personal variables
     */

    /**
     *
     * @var /date
     *
     * @ORM\Column(name="creationDate", type="date", nullable=false)
     */
    private $creationDate;

    /*
     * Autogenerated variables
     */

    /**
     *
     * @var int
     *
     * @ORM\Column(name="id",               type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=32)
     *
     * @Assert\NotBlank(
     *      message = "Veuillez saisir un nom"
     * )
     * @Assert\Length(
     *      min = 2,
     *      max = 32,
     *      minMessage = "Votre nom doit contenir au minimum {{ limit }} caractères",
     *      maxMessage = "Votre nom doit contenir au maximum {{ limit }} caractères"
     * )
     */
    private $name;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="nameCanonical", type="string", length=32, nullable=true)
     */
    private $nameCanonical;

    /**
     *
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     *
     * @Assert\NotBlank(
     *     message= "Veuillez détailler votre offre"
     * )
     * @Assert\Length(
     *      min = 16,
     *      max = 250,
     *      minMessage = "Votre description doit contenir au minimum {{ limit }} caractères",
     *      maxMessage = "Votre description doit contenir au maximum {{ limit }} caractères"
     * )
     */
    private $description;

    /**
     *
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date")
     *
     * @Assert\NotBlank(
     *     message="Veuillez saisir une date"
     * )
     * @Assert\Date()
     */
    private $date;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="amount", type="integer")
     *
     * @Assert\Type(
     *     type="integer",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     *
     * @Assert\Range(
     *     min = 200,
     *     minMessage = "Veuillez saisir un montant minimal de 200€."
     * )
     */
    private $amount;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="handlingFee", type="integer", nullable=true)
     */
    private $handlingFee;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="partnershipNumber", type="integer")
     *
     * @Assert\Type(
     *     type="integer",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     * @Assert\Range(
     *      min = 1,
     *      minMessage = "Le nombre de partenaire(s) ne peut être inférieur à {{ limit }}"
     * )
     */
    private $partnershipNumber;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="finalDeal", type="integer", nullable=true)
     */
    private $finalDeal;

    /**
     *
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     *
     * @var bool
     *
     * @ORM\Column(name="signature", type="boolean", nullable=true)
     */
    private $signature;

    /*
     * Add Personal Method
     */

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->setStatus(0);
        $this->setCreationDate(new \DateTime());
    }

    /*
     * Autogenerated methods
     */

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Offer
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set nameCanonical
     *
     * @param string $nameCanonical
     *
     * @return Offer
     */
    public function setNameCanonical($nameCanonical)
    {
        $this->nameCanonical = $nameCanonical;

        return $this;
    }

    /**
     * Get nameCanonical
     *
     * @return string
     */
    public function getNameCanonical()
    {
        return $this->nameCanonical;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Offer
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Offer
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set amount
     *
     * @param integer $amount
     *
     * @return Offer
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * Get amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Set handlingFee
     *
     * @param integer $handlingFee
     *
     * @return Offer
     */
    public function setHandlingFee($handlingFee)
    {
        $this->handlingFee = $handlingFee;

        return $this;
    }

    /**
     * Get handlingFee
     *
     * @return int
     */
    public function getHandlingFee()
    {
        return $this->handlingFee;
    }

    /**
     * Set partnershipNumber
     *
     * @param integer $partnershipNumber
     *
     * @return Offer
     */
    public function setPartnershipNumber($partnershipNumber)
    {
        $this->partnershipNumber = $partnershipNumber;

        return $this;
    }

    /**
     * Get partnershipNumber
     *
     * @return int
     */
    public function getPartnershipNumber()
    {
        return $this->partnershipNumber;
    }

    /**
     * Set finalDeal
     *
     * @param integer $finalDeal
     *
     * @return Offer
     */
    public function setFinalDeal($finalDeal)
    {
        $this->finalDeal = $finalDeal;

        return $this;
    }

    /**
     * Get finalDeal
     *
     * @return int
     */
    public function getFinalDeal()
    {
        return $this->finalDeal;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return Offer
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set signature
     *
     * @param boolean $signature
     *
     * @return Offer
     */
    public function setSignature($signature)
    {
        $this->signature = $signature;

        return $this;
    }

    /**
     * Get signature
     *
     * @return bool
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Set activity
     *
     * @param \AppBundle\Entity\Activity $activity
     *
     * @return Offer
     */
    public function setActivity(Activity $activity)
    {
        $this->activity = $activity;

        return $this;
    }

    /**
     * Get activity
     *
     * @return \AppBundle\Entity\Activity
     */
    public function getActivity()
    {
        return $this->activity;
    }

    /**
     * Set creationDate.
     *
     * @param \DateTime $creationDate
     *
     * @return Offer
     */
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Get creationDate.
     *
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Set organization.
     *
     * @param Organization $organization
     *
     * @return Offer
     */
    public function setOrganization(Organization $organization)
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * Get organization.
     *
     * @return Organization
     */
    public function getOrganization()
    {
        return $this->organization;
    }
}
